image: node:latest
services:

cache:
  paths:
    - node_modules/
    - public/stylesheets/

# test_gulp:
#   script:
#     - ./bin/install.sh
#     - npm run build

github_deploy:
  before_script:
  - su
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  script:
    - git pull origin master
    - git checkout master
    - git remote rm origin
    - git remote add origin git@github.com:MarleyPlant/Plugit
    - git config --global user.email "marley@marleyplant.com"
    - git config --global user.name "Marley Plant"
    - git commit --amend --no-edit
    - git push origin master -f
  rules :
    - if: $CI_COMMIT_REF_NAME != "master" && $CI_COMMIT_TAG != ""
      when: on_success
    - when: never


# test_mocha:
#   script:
#     - ./bin/install.sh
#     - npm run test

# test_async:
#   script:
#     - bin/install.sh
#     - npm start

# test_knex:
#   script:
#     - bin/install.sh
#     - npm run migrate