image: node:latest
services:

cache:
  paths:
    - node_modules/
    - public/stylesheets/

# test_gulp:
#   script:
#     - ./bin/install.sh
#     - npm run build

# test_mocha:
#   script:
#     - ./bin/install.sh
#     - npm run test

# test_async:
#   script:
#     - bin/install.sh
#     - npm start

# test_knex:
#   script:
#     - bin/install.sh
#     - npm run migrate