version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
      port: 5000

  bot:
    build: ./bot
    depends_on:
      - postgres
      - frontend
    environment:
      port: 5000

  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: plugit
      POSTGRES_PASSWORD: admin

  migration:
    image: new_frontend:latest
    command: ["npm", "run", "migrate"]
    links:
      - postgres
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
